---
driver:
  hostname: test # Hostname is used in the tests so should be fixed
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: debian-10
    driver:
      image: dokken/debian-10
      pid_one_command: /bin/systemd
      privileged: true

suites:
  - name: no-attribute-test
    run_list:
      - recipe[kontextwork-helpers-lib-test::attribute_test]
  - name: attribute-test
    run_list:
      - recipe[kontextwork-helpers-lib-test::attribute_test]
    attributes:
      mykey:
        nested1: 'kitchen arg'
  - name: default-attribute-test
    run_list:
      - recipe[kontextwork-helpers-lib-test::attribute_test]
    default_attributes:
      mykey:
        nested1: 'kitchen arg'
  - name: role-attribute-test
    run_list:
      - role[attribute_test]
